### ISSUE TITLE
How to get this working?

### ISSUE THREAD

**Issue by rna7** [lovac42/LeitnerEmulator#2]
Hi. This looks like a great idea, but I have no idea how to set this up for basic leitner flashcards even after reading your instructions. 
Can you give me a step by step guide? Thanks

**Comment by lovac42** [comment]
I added some baby steps: https://github.com/lovac42/LeitnerEmulator#leitner-baby-step-setup

**Comment by rna7** [comment]
That's awesome. Thanks so much.

**Comment by rna7** [comment]
I've just tested this, and it works good. Just wondering is there a way to auto rebuild all filtered decks?

**Comment by lovac42** [comment]
I haven't look into it, but I don't feel like screwing around with those code.

There are two options available for you:
1) Study from the main deck, all cards from all boxes due today will be reviewed. (Similar to Leitner proficiency levels.)
2) Edit the script, set REPEAT_IN_FILTER_DECK to True. This will allow it to repeat in the same filter deck session. It will keep repeating until you hit the good or easy button. Then you need to rebuild and start again.

**Comment by rna7** [comment]
Okay I see. Thanks for reply. I guess I will keep as is then.
